"""Add file_type field to TaskFile

Revision ID: d674cb0540c6
Revises: 
Create Date: 2025-10-14 15:19:07.222323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd674cb0540c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_files', schema=None) as batch_op:
        batch_op.drop_column('file_type')

    # ### end Alembic commands ###
