"""Add description field to TaskFile

Revision ID: f734b0cf8fb6
Revises: d674cb0540c6
Create Date: 2025-10-14 15:32:09.651040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f734b0cf8fb6'
down_revision = 'd674cb0540c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_files', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
